apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infra-agent.fullname" . }}-secrets
  labels:
    app: {{ include "infra-agent.name" . }}
    chart: {{ include "infra-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  OPENAI_MODEL: {{ .Values.settings.openaiModel | quote }}
  OPENAI_API_KEY: {{ .Values.settings.openaiApiKey | quote }}
  GRAFANA_API_KEY: {{ .Values.settings.grafana.apiKey | quote }}
  GITLAB_TOKEN: {{ .Values.settings.gitlab.token | quote }}
