name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

env:
  GIT_SHA: ${{ github.sha }}
  CONTAINER_NAME: infra-agent
  CHART_NAME: infra-agent
  BOT_USER_NAME: szymonrichert.pl bot
  BOT_USER_EMAIL: bot@szymonrichert.pl
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
  HARBOR_URL: harbor.szymonrichert.pl

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Load cached pre-commit
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up Python 3.12.2
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: 3.12.2

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
        with:
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true --local
          poetry config virtualenvs.create true --local
          poetry install --no-interaction
        shell: bash

      - name: Linters
        run: |
          poetry run pre-commit run -a

      # - name: Pytest
      #   run: |
      #     poetry run coverage run -m pytest
      #     poetry run coverage report -m

  build:
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Parse versions in commit and setup debs for tag
        id: prep
        run: |
          export LATEST_REPO_TAG=$(git tag -l --sort=-v:refname "[0-9]*" | head -n1)
          if [ -z "${LATEST_REPO_TAG}" ]; then
            export LATEST_REPO_TAG="0.0.0"
          fi
          export SHORT_SHA=$(echo ${GIT_SHA:0:7})
          export APP_VERSION=${LATEST_REPO_TAG}-${SHORT_SHA}
          export CHART_VERSION=${LATEST_REPO_TAG}-${SHORT_SHA}
          export CONTAINER_VERSION=${GIT_SHA:0:7}

          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "chart_version=${CHART_VERSION}" >> $GITHUB_OUTPUT
          echo "container_version=${CONTAINER_VERSION}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "latest_repo_tag=${LATEST_REPO_TAG}" >> $GITHUB_OUTPUT

      - name: Login to container registry
        run: |
          set -e
          echo "$HARBOR_PASSWORD" | \
            docker login "https://${HARBOR_URL}/containers" \
              -u "$HARBOR_USERNAME" \
              --password-stdin

      - name: Login to chart registry
        run: |
          set -e
          echo "$HARBOR_PASSWORD" \
            | helm registry login "oci://${HARBOR_URL}/charts" \
              -u "$HARBOR_USERNAME" \
              --password-stdin

      - name: Build new container for branch
        run: |
          set -e

          docker build -t "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.short_sha }}" .

          docker tag "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.short_sha }}" "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.container_version }}"

          docker push "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.short_sha }}"
          docker push "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.container_version }}"

      - name: Package and upload charts
        run: |
          set -e
          helm package \
            --dependency-update "./chart/${CHART_NAME}" \
            --version ${{ steps.prep.outputs.chart_version }} \
            --app-version ${{ steps.prep.outputs.container_version }} \
            -u -d ./ "./chart/${CHART_NAME}"

          helm push "${CHART_NAME}-${{ steps.prep.outputs.chart_version }}.tgz" "oci://${HARBOR_URL}/charts"
