name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GIT_SHA: ${{ github.sha }}
  CONTAINER_NAME: infra-agent
  CHART_NAME: infra-agent
  BOT_USER_NAME: szymonrichert.pl bot
  BOT_USER_EMAIL: bot@szymonrichert.pl
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
  HARBOR_URL: harbor.szymonrichert.pl

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Parse versions in commit and setup debs for tag
        id: prep
        run: |
          export LATEST_REPO_TAG=$(git tag -l --sort=-v:refname "[0-9]*" | head -n1)

          export SHORT_SHA="$(echo ${GIT_SHA:0:7})"
          export APP_VERSION="${LATEST_REPO_TAG}"
          export CHART_VERSION="${LATEST_REPO_TAG}"
          export CONTAINER_VERSION="${LATEST_REPO_TAG}"

          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "chart_version=${CHART_VERSION}" >> $GITHUB_OUTPUT
          echo "container_version=${CONTAINER_VERSION}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "latest_repo_tag=${LATEST_REPO_TAG}" >> $GITHUB_OUTPUT

      - name: Login to container registry
        run: |
          set -e
          echo "$HARBOR_PASSWORD" | \
            docker login "https://${HARBOR_URL}/containers" \
              -u "$HARBOR_USERNAME" \
              --password-stdin

      - name: Login to chart registry
        run: |
          set -e
          echo "$HARBOR_PASSWORD" \
            | helm registry login "oci://${HARBOR_URL}/charts" \
              -u "$HARBOR_USERNAME" \
              --password-stdin

      - name: Tag existing container for release
        run: |
          set -e
          docker pull "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.short_sha }}"
          docker tag "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.short_sha }}" "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.container_version }}"
          docker push "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.container_version }}"

          docker tag "${HARBOR_URL}/containers/${CONTAINER_NAME}:${{ steps.prep.outputs.short_sha }}" "${HARBOR_URL}/containers/${CONTAINER_NAME}:latest"
          docker push ${HARBOR_URL}/containers/${CONTAINER_NAME}:latest

      - name: Package and upload charts
        run: |
          set -e
          helm package \
            --dependency-update "./chart/${CHART_NAME}" \
            --version ${{ steps.prep.outputs.chart_version }} \
            --app-version ${{ steps.prep.outputs.container_version }} \
            -u -d ./ "./chart/${CHART_NAME}"

          helm push "${CHART_NAME}-${VERSION}.tgz" "oci://${HARBOR_URL}/charts"


      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME"
